id: ICF45A905
source: null
source_file: null
initial_creation_type: input
imported: '2022-06-30T14:41:18.595953'
last_modified: '2022-06-30T14:41:18.596013'
parser: null
source_metadata:
  title: ༄། །བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་བཞུགས་སོ།
  language: bo
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
